### ISSUE TITLE
AddressBook-Lvl2 Unable to run runtests.bat

### ISSUE THREAD

**Issue by ck94rec** [nus-cs2103-AY1718S2/forum#12]
Hi, while doing the LOs i encountered a problem with the runtests.bat.

Java Version: Java 8 (1.8.0_162)
Project Language Level: 8 - Lambdas, type annotations etc.
Tried: 
Adding java 8 bin folder into environment variables and restarting computer
Using Java 8 1.8.0_161 version

Note: 
All in test (Junit test) were able to run successfully, passing all the test cases.
Submitting pull request, Travis CI Build were able to pass.
However, upon running testcase.bat (runtests), the error below occurs.

cmd.exe /c runtests.bat
..\src\seedu\addressbook\storage\StorageFile.java:7: error: package javax.xml.bind is not visible
import javax.xml.bind.JAXBContext;
                ^
  (package javax.xml.bind is declared in module java.xml.bind, which is not in the module graph)
..\src\seedu\addressbook\storage\StorageFile.java:8: error: package javax.xml.bind is not visible
import javax.xml.bind.JAXBException;
                ^
  (package javax.xml.bind is declared in module java.xml.bind, which is not in the module graph)
..\src\seedu\addressbook\storage\StorageFile.java:9: error: package javax.xml.bind is not visible
import javax.xml.bind.Marshaller;
                ^
  (package javax.xml.bind is declared in module java.xml.bind, which is not in the module graph)
..\src\seedu\addressbook\storage\StorageFile.java:10: error: package javax.xml.bind is not visible
import javax.xml.bind.Unmarshaller;
                ^
  (package javax.xml.bind is declared in module java.xml.bind, which is not in the module graph)
..\src\seedu\addressbook\storage\jaxb\AdaptedAddressBook.java:11: error: package javax.xml.bind.annotation is not visible
import javax.xml.bind.annotation.XmlElement;
                     ^
  (package javax.xml.bind.annotation is declared in module java.xml.bind, which is not in the module graph)
..\src\seedu\addressbook\storage\jaxb\AdaptedAddressBook.java:12: error: package javax.xml.bind.annotation is not visible
import javax.xml.bind.annotation.XmlRootElement;
                     ^
  (package javax.xml.bind.annotation is declared in module java.xml.bind, which is not in the module graph)
..\src\seedu\addressbook\storage\jaxb\AdaptedPerson.java:6: error: package javax.xml.bind.annotation is not visible
import javax.xml.bind.annotation.XmlAttribute;
                     ^
  (package javax.xml.bind.annotation is declared in module java.xml.bind, which is not in the module graph)
..\src\seedu\addressbook\storage\jaxb\AdaptedPerson.java:7: error: package javax.xml.bind.annotation is not visible
import javax.xml.bind.annotation.XmlElement;
                     ^
  (package javax.xml.bind.annotation is declared in module java.xml.bind, which is not in the module graph)
..\src\seedu\addressbook\storage\jaxb\AdaptedPerson.java:8: error: package javax.xml.bind.annotation is not visible
import javax.xml.bind.annotation.XmlValue;
                     ^
  (package javax.xml.bind.annotation is declared in module java.xml.bind, which is not in the module graph)
..\src\seedu\addressbook\storage\jaxb\AdaptedTag.java:7: error: package javax.xml.bind.annotation is not visible
import javax.xml.bind.annotation.XmlValue;
                     ^
  (package javax.xml.bind.annotation is declared in module java.xml.bind, which is not in the module graph)
10 errors
Error: Could not find or load main class seedu.addressbook.Main
Caused by: java.lang.ClassNotFoundException: seedu.addressbook.Main
Comparing files actual.txt and EXPECTED.TXT
Resync Failed.  Files are too different.
***** actual.txt
***** EXPECTED.TXT
|| ===================================================
|| ===================================================
|| Welcome to your Address Book!
|| AddressBook Level 2 - Version 1.0
|| Launch command format: java seedu.addressbook.Main [STORAGE_FILE_PATH]
|| Using storage file : addressbook.xml
|| ===================================================
|| Enter command: || [Command entered:  sfdfd]
|| add: Adds a person to the address book. Contact details can be marked private by prepending 'p' to the prefix.
|| Parameters: NAME [p]p/PHONE [p]e/EMAIL [p]a/ADDRESS  [t/TAG]...
|| Example: add John Doe p/98765432 e/johnd@gmail.com a/311, Clementi Ave 2, #02-25 t/friends t/owesMoney
|| delete: Deletes the person identified by the index number used in the last person listing.
|| Parameters: INDEX
|| Example: delete 1
|| Clears address book permanently.
|| Example: clear
|| find: Finds all persons whose names contain any of the specified keywords (case-sensitive) and displays them as a list with 
index numbers.
|| Parameters: KEYWORD [MORE_KEYWORDS]...
|| Example: find alice bob charlie
|| list: Displays all persons in the address book as a list with index numbers.
|| Example: list
|| view: Views the non-private details of the person identified by the index number in the last shown person listing.
|| Parameters: INDEX
|| Example: view 1
|| viewall: Views the non-private details of the person identified by the index number in the last shown person listing.
|| Parameters: INDEX
|| Example: viewall 1
|| help: Shows program usage instructions.
|| Example: help
|| exit: Exits the program.
|| Example: exit
|| ===================================================
|| Enter command: || [Command entered:  delete 1]
|| The person index provided is invalid
|| ===================================================
|| Enter command: || [Command entered:  view 1]
|| The person index provided is invalid
|| ===================================================
|| Enter command: || [Command entered:  viewall 1]
|| The person index provided is invalid
|| ===================================================
|| Enter command: || [Command entered:  clear]
|| Address book has been cleared!
|| ===================================================
|| Enter command: || [Command entered:  list]
|| 
|| 0 persons listed!
|| ===================================================
|| Enter command: || [Command entered:  add wrong args wrong args]
|| Invalid command format! 
|| add: Adds a person to the address book. Contact details can be marked private by prepending 'p' to the prefix.
|| Parameters: NAME [p]p/PHONE [p]e/EMAIL [p]a/ADDRESS  [t/TAG]...
|| Example: add John Doe p/98765432 e/johnd@gmail.com a/311, Clementi Ave 2, #02-25 t/friends t/owesMoney
|| ===================================================
|| Enter command: || [Command entered:  add Valid Name 12345 e/valid@email.butNoPhonePrefix a/valid, address]
|| Invalid command format! 
|| add: Adds a person to the address book. Contact details can be marked private by prepending 'p' to the prefix.
|| Parameters: NAME [p]p/PHONE [p]e/EMAIL [p]a/ADDRESS  [t/TAG]...
|| Example: add John Doe p/98765432 e/johnd@gmail.com a/311, Clementi Ave 2, #02-25 t/friends t/owesMoney
|| ===================================================
|| Enter command: || [Command entered:  add Valid Name p/12345 valid@email.butNoPrefix a/valid, address]
|| Invalid command format! 
|| add: Adds a person to the address book. Contact details can be marked private by prepending 'p' to the prefix.
|| Parameters: NAME [p]p/PHONE [p]e/EMAIL [p]a/ADDRESS  [t/TAG]...
|| Example: add John Doe p/98765432 e/johnd@gmail.com a/311, Clementi Ave 2, #02-25 t/friends t/owesMoney
|| ===================================================
|| Enter command: || [Command entered:  add Valid Name p/12345 e/valid@email.butNoAddressPrefix valid, address]
|| Invalid command format! 
|| add: Adds a person to the address book. Contact details can be marked private by prepending 'p' to the prefix.
|| Parameters: NAME [p]p/PHONE [p]e/EMAIL [p]a/ADDRESS  [t/TAG]...
|| Example: add John Doe p/98765432 e/johnd@gmail.com a/311, Clementi Ave 2, #02-25 t/friends t/owesMoney
|| ===================================================
|| Enter command: || [Command entered:  add Valid Name p/12345 e/valid@email.butNoTagPrefix a/valid, address t/goodTag noPrefix
Tag]
|| Tags names should be alphanumeric
|| ===================================================
|| Enter command: || [Command entered:  add []\[;] p/12345 e/valid@e.mail a/valid, address]
|| Person names should be spaces or alphabetic characters
|| ===================================================
|| Enter command: || [Command entered:  add Valid Name p/not_numbers e/valid@e.mail a/valid, address]
|| Person phone numbers should only contain numbers
|| ===================================================
|| Enter command: || [Command entered:  add Valid Name p/12345 e/notAnEmail a/valid, address]
|| Person emails should be 2 alphanumeric/period strings separated by '@'
|| ===================================================
|| Enter command: || [Command entered:  add Valid Name p/12345 e/valid@e.mail a/valid, address t/invalid_-[.tag]
|| Tags names should be alphanumeric
|| ===================================================
|| Enter command: || [Command entered:  add Adam Brown p/111111 e/adam@gmail.com a/111, alpha street]
|| New person added: Adam Brown Phone: 111111 Email: adam@gmail.com Address: 111, alpha street Tags: 
|| ===================================================
|| Enter command: || [Command entered:  list]
||      1. Adam Brown Phone: 111111 Email: adam@gmail.com Address: 111, alpha street Tags: 
|| 
|| 1 persons listed!
|| ===================================================
|| Enter command: || [Command entered:  add Betsy Choo pp/222222 pe/benchoo@nus.edu.sg pa/222, beta street t/secretive]
|| New person added: Betsy Choo Phone: (private) 222222 Email: (private) benchoo@nus.edu.sg Address: (private) 222, beta street
 Tags: [secretive]
*****

Process finished with exit code 1

**Comment by okkhoy** [comment]
Can you check if the paths are set properly? Particularly since you say:

> All in test (Junit test) were able to run successfully, passing all the test cases.
> Submitting pull request, Travis CI Build were able to pass.

**Comment by ck94rec** [comment]
By path do u mean the environment variables path? If so i have checked and its correct.
![image](https://user-images.githubusercontent.com/35593675/36241446-58e2f98c-1251-11e8-84e9-5cb917a68079.png)

Dont know if this will help but this is a screenshot of the Project Structure Module
![image](https://user-images.githubusercontent.com/35593675/36241415-226b3586-1251-11e8-8646-74ddfb074b34.png)
![image](https://user-images.githubusercontent.com/35593675/36241475-87505d00-1251-11e8-86dd-34d288adb315.png)

**Comment by tanhengyeow** [comment]
In your `runtests.bat` file, add the following changes and see if it works for you.

java -classpath ..\bin `--add-modules java.xml.bind` seedu.addressbook.Main < input.txt > actual.txt

**Comment by ck94rec** [comment]
Tried the add modules method, to no avail still...

**Comment by okkhoy** [comment]
Since you have two installations of JDK, I suspect it is causing troubles. From what I hear, setting the add-modules should help. 
Can you try removing one of the JDK from the path? If that doesn't work, I am afraid, I am unable to think of anything else other than clean up the Java/JDK installations and install one of them afresh.

**Comment by kokonguyen191** [comment]
Have you solved the issue? If not, have you tried uninstalling both versions and installing only 1.8.0_162? From what I see, it looks like javac couldn't compile anything as the bin folder is empty.

**Comment by ck94rec** [comment]
Hi! Deleting other version of JDK and JDE solved the problem! Thank you so much :)

**Comment by Zhiyuan-Amos** [comment]
@e0052813 hello! I would like to check if you set the value of `$JAVA_HOME` to use that of JDK8. That's because when mine was set to JDK9, I faced the same issue as you. However, when I've changed it to JDK8, it passes. :)
