### ISSUE TITLE
BUG : Fragile System tests

### ISSUE THREAD

**Issue by ng95junwei** [nus-cs2103-AY1718S2/forum#31]
Bug in System test:

I made a clean PR from a version that passed the CI:

https://github.com/ng95junwei/main [Passes the CI build]

https://github.com/ng95junwei/main/tree/add-email-command [Fails the CI build]

https://github.com/CS2103JAN2018-W10-B4/main/pull/46/files [Code diff]

However, the System tests fails because the ResultDisplay does not reflect the CommandResult. 

![image](https://user-images.githubusercontent.com/9381976/37693012-a4de6cac-2cf7-11e8-8cd1-ec2297d8fff9.png)

On testing manually (By running the MainApp), ResultDisplay does show the CommandResult

![image](https://user-images.githubusercontent.com/9381976/37693351-0e23626a-2cfa-11e8-89af-1f2fc8bfa6d4.png)

Please let me know if you need any more information to help debug.

**Comment by yamgent** [comment]
Hi @ng95junwei, thanks for your post.

The symptoms that you have reported looks very similar to [a case we had recently](https://github.com/se-edu/addressbook-level4/issues/849). Can you try doing the following:

> Simply upgrade your gradle version from 2.12 to 4.6

Let us know if that solves the problem or not. Thanks!

**Comment by Zhiyuan-Amos** [comment]
@yamgent was just about to comment but you beat me to it :P

**Comment by tshradheya** [comment]
@Zhiyuan-Amos , I told the @ng95junwei  to post the issue on the forum and I told him I would tag you to help him solve the issue 😆 but you guys are very fast :P

**Comment by ng95junwei** [comment]
Hi  @yamgent @Zhiyuan-Amos @tshradheya,

Thanks for the really quick replies! Build is working fine now!

**Comment by chenxing1992** [comment]
Hi, i am facing this problem too. My local project works fine after i upgrade gradle version to 4.6. However, when pull to Github, Travis fails all my test cases. Can anyone help me out? 
Apparently, i check the travis gradle version it is 4.0.1

<img width="605" alt="screen shot 2018-03-25 at 8 48 42 pm" src="https://user-images.githubusercontent.com/35635056/37875318-a51f0d04-306f-11e8-9d13-cde59f4d7209.png">


@yamgent @Zhiyuan-Amos

**Comment by Zhiyuan-Amos** [comment]
@chenxing1992 Hi Chen Xing! Please include a link to your PR so that we can take a further look :)

**Comment by chenxing1992** [comment]
This is the link to travis: https://travis-ci.org/CS2103JAN2018-T09-B4/main/builds/358154192?utm_source=github_status&utm_medium=notification
This is the link to PR: https://github.com/CS2103JAN2018-T09-B4/main/pull/90

Currently after i upgraded my gradle version to 4.6 and did a headless check like the one travis had.
However, travis fails most of the system test in systemtests directory which i never touch before  but my local project pass (build successfully).

I uses this check: ./gradlew clean checkstyleMain checkstyleTest headless allTests coverage coveralls asciidoctor copyDummySearchPage

Thanks for the help! =D @Zhiyuan-Amos

**Comment by Zhiyuan-Amos** [comment]
I'll reply you on your PR :)
