### ISSUE TITLE
Fragile System test #2

### ISSUE THREAD

**Issue by chenxing1992** [nus-cs2103-AY1718S2/forum#33]
I need to upgrade my gradle version to 4.6 because the testcase malfuntioned in older version. And it works fine after i upgraded my gradle version to 4.6 and did a headless check like the one travis had. 
However, travis fails my system test but my local project pass. Does anyone know why?

**Comment by Zhiyuan-Amos** [comment]
@okkhoy can close this issue, see https://github.com/se-edu/addressbook-level4/issues/862

**Comment by okkhoy** [comment]
Issue resolved in @chenxing1992 PR's conversation.
Thanks @Zhiyuan-Amos 😍 😜
