### ISSUE TITLE
Issue with running MainApp.main()

### ISSUE THREAD

**Issue by ghost** [nus-cs2103-AY1718S2/forum#34]
Hi, anyone also having issue with this NullPointerException "input stream must not be null" being thrown when you try to run MainApp.main()??

![image](https://user-images.githubusercontent.com/35895966/37903831-f684ebf2-312b-11e8-9eaf-fcd8152c6549.png)

It's weird because my ICON_APPLICATION should be pointing correctly to the relative path of address_book_32.png which is /images/address_book_32.png (I also checked and verified that file is indeed under src\main\resources\images.

![image](https://user-images.githubusercontent.com/35895966/37903908-507e0364-312c-11e8-9bed-788ace34362e.png)

And moreover please refer to this link: https://github.com/nus-cs2103-AY1718S2/addressbook-level4/blob/master/src/main/resources/images/address_book_32.png

Any help would be appreciated! Thank you very much! :)

**Comment by Zhiyuan-Amos** [comment]
Upstream dev here. I sometimes get this too, I think deleting the repo and re-cloning it should do the trick.

Edit: maybe try running `gradlew processResources`? I can't exactly remember how I fixed this, but this was something I recall that I tried doing

**Comment by ghost** [comment]
Hi I tried the `gradlew processResources` but it still does not work (edit: actually it solves the "input stream must not be null" problem but another problem now in other areas of the project).

![image](https://user-images.githubusercontent.com/35895966/37947162-1b234f9a-31bc-11e8-9927-af9080678c18.png)

I think there was a former issue similar to this which was created before? I will go check it out!

Just checking, run/debug configurations for the MainApp should be like this below right?
![image](https://user-images.githubusercontent.com/35895966/37947200-4d8e67e4-31bc-11e8-89cd-437b281d17b8.png)

Should the classpath of the module be main, GitHub-main or main_main?
![image](https://user-images.githubusercontent.com/35895966/37947215-70fda064-31bc-11e8-8850-2fd6d7f68a45.png)

The folder I put all my GitHub projects is called "GitHub" i.e. inside contains addressbook-level1, addressbook-level2, addressbook-level3. I named the repo of my addressbook-level4 as "main" and I put that inside a folder called "main" inside too.
![image](https://user-images.githubusercontent.com/35895966/37947259-b2da5b44-31bc-11e8-972f-0dea63af2a6a.png)

![image](https://user-images.githubusercontent.com/35895966/37947317-087be716-31bd-11e8-9f4a-8acf56366b0a.png)

**Comment by Zhiyuan-Amos** [comment]
I'll let someone else reply for this issue :p

**Comment by ghost** [comment]
Actually the "input stream must not be null" issue is still there even after `gradlew processResources`

**Comment by Zhiyuan-Amos** [comment]
Have you tried deleting your project and re-cloning it?

**Comment by ghost** [comment]
You mean deleting my local "main" repo which is a clone of the forked remote "main" repo (which is on my GitHub profile) which is forked from the upstream aka AY1718S2-address book level 4 only?

Or delete my remote fork even too?

(I am scared that if I have to delete my remote fork, previous commits I made to my group's project and shown in the PR of our group to the level 4 address book, they will say they are commits from an "unknown repo")

**Comment by Zhiyuan-Amos** [comment]
Ok I've taken a further look into this issue, so you also need `address_book_32.png` in `addressbook-level4\out\production\resources\images`.

I forgot how to generate it automatically, but I'll take a look into it :) One way is to simply delete the `addressbook-level4\out` folder, and just run the app again, it will auto-generate the folder with `address_book_32.png` inside.

This method is easier than deleting your project :P

Edit: The `out` folder is generated by IntelliJ. I think when IntelliJ first builds your project (i.e. the `out` folder does not yet exist), IntelliJ will generate the `out` folder.

**Comment by ghost** [comment]
Hi Amos,

Okay that does make sense. I will try that out soon later as my laptop is not currently at my side.

Hoping to share good news soon! 🙂

**Comment by ghost** [comment]
Hmm,

I've done what you said and it doesn't seem to solve the issue. One thing I didn't do after that was the `graddlew processResources` though.

Perhaps deleting my local repo and recloning it from my remote on my GitHub account is the only way now? (with necessary setup settings such as the aforementioned `gradlew processResources` too and etc)

![image](https://user-images.githubusercontent.com/35895966/37957525-c2121d30-31e0-11e8-8851-a00bf8df0a7e.png)

**Comment by ghost** [comment]
This is how the contents inside the generated `out` folder looks like (there isn't even an `image` folder generated inside `main\out\production\main\seedu\address`):

![image](https://user-images.githubusercontent.com/35895966/37957784-68e38e0a-31e1-11e8-91c7-97b505ef01d7.png)

![image](https://user-images.githubusercontent.com/35895966/37957814-7bf40c90-31e1-11e8-8b03-f07340d15f74.png)

**Comment by Zhiyuan-Amos** [comment]
You went to `out\production\main`, but it should be `out\production\resources\images`. I'm using a Mac though, not sure whether it affects the directory. Can you check if `out\production\resources\images` exists for you?

> Perhaps deleting my local repo and recloning it from my remote on my GitHub account is the only way now? (with necessary setup settings such as the aforementioned gradlew processResources too and etc)

Yup, this is the worst case scenario I guess. :(

**Comment by ghost** [comment]
Good evening Amos,

In reply to your question, there is no `out\production\resources\images` folder at all and only `out\production\main` i.e. there is only a `main` folder inside `out\production` but no `resources` folder inside for some weird reason, after I ran MainApp.main() in IntelliJ IDEA.

![image](https://user-images.githubusercontent.com/35895966/37973885-1ce83c80-320e-11e8-908a-91c0210f9e7b.png)

Maybe I will just do the worst-case scenario solution if all else fails, haha..

**Comment by ghost** [comment]
Hi,

I have deleted and re-cloned my local repo.

Call me noob, but I realize there is no `out\production` folder in the first place when I cloned the remote from GitHub XD This is how it looks like (when I have not ran the `MainApp.main()` yet)

![image](https://user-images.githubusercontent.com/35895966/37977155-ce1daa2e-3215-11e8-90ba-9e299561658e.png)
![image](https://user-images.githubusercontent.com/35895966/37977238-f1a35106-3215-11e8-8811-6d6619399013.png)

Build was successful also when I ran the command `gradlew clean checkstyleMain checkstyleTest headless allTests coverage coveralls asciidoctor` in terminal too :)

![image](https://user-images.githubusercontent.com/35895966/37977396-351783e4-3216-11e8-8105-9e8fa98955ee.png)

Next step is to actually try running `MainApp.main()` to see if the AddressBook can open up as intended

EDIT:
I realized, by default, when you have not ran a project yet, the `edit configurations` will look like this when you open it up:
![image](https://user-images.githubusercontent.com/35895966/37977532-75d6e08c-3216-11e8-9c42-b4e514e70253.png)
![image](https://user-images.githubusercontent.com/35895966/37977549-7e9c6098-3216-11e8-9c4a-152cf929c356.png)

so yeah... even though I guess I am learning a bit slow, I still learn more and more things every time! =)

**Comment by Zhiyuan-Amos** [comment]
@HEARTOFAL1ON I'll try running on my Windows PC and see how my `out` directory looks like. 

> there is no out\production folder in the first place when I cloned the remote from GitHub XD

That's right, the folder is only created when IntelliJ builds your project. IntelliJ uses the files in the `out` folder for the program execution. Gradle doesn't create the `out` folder and the files inside the `out` folder because it doesn't use it for program execution I think.

**Comment by ghost** [comment]
GOOD NEWS!!

IT WORKS AS INTENDED!

![image](https://user-images.githubusercontent.com/35895966/37977669-ccef7fe6-3216-11e8-8f8d-dcb3c624d880.png)

I think this issue may be closed now. Thank you so much for your help rendered so far!

Yes, maybe this is a funny bug which even upstream developers like yourself occur! Haha.. Or maybe I used the wrong term, maybe not bug but glitch or whatever instead?

P.S. If there are any further issues (that are not specific to my project and require downstream developers i.e. my team members and myself) to debug ourselves, there is no harm raising issues in this forum right? :):)

>I'll try running on my Windows PC and see how my out directory looks like.

wow @Zhiyuan-Amos you must be very proficient to be able to alternate between both Windows and Mac efficiently, HAHA..

**Comment by Zhiyuan-Amos** [comment]
Yay great!!! ^^ Can you check if you have the directory `out\production\resources\images`?

> P.S. If there are any further issues (that are not specific to my project and require downstream developers i.e. my team members and myself) to debug ourselves, there is no harm raising issues in this forum right? :):)

Haha idk, I'm not a TA :p I'm just a student taking CS3282 and working on AddressBook-Level4 now. 

> even though I guess I am learning a bit slow, I still learn more and more things every time! =)

Haha yup, after working on this project for quite some time, there's still bugs / glitches like this one that you raised that I still don't know how to resolve XD

**Comment by ghost** [comment]
>I'm just a student taking CS3282

Wow, what mod is that? * checks NUSMods * I'm not a computing/infosec student so yeah ><. Don't ever have to take such high level CS mod, HAHA..

But other faculties one, have to lah... :/ OH WELL, such is life man.... =)

Actually is it okay to sometimes have casual convos like this even on a particular issue in this forum? Hahaha... Yeah, maybe someone like Akshay close this issue soon :)

**Comment by Zhiyuan-Amos** [comment]
> Wow, what mod is that?

It's the follow-up Software Engineering module from CS2103, so if you have UEs, you can try taking this mod :)

> Actually is it okay to sometimes have casual convos like this even on a particular issue in this forum? 

You are the first to be so casual on the forum in this semester and the past semester HAHA XD
