### ISSUE TITLE
About Location Finder major enhancement

### ISSUE THREAD

**Issue by ghost** [nus-cs2103-AY1718S2/forum#36]
Hi all,

My _major_ enhancement is about a `Location Finder`. According to https://developers.google.com/maps/documentation/urls/guide, the String URL format of a Google Maps search query is `https://www.google.com/maps/search/?api=1&parameters`.

For example, I want to search where NUS Museum is located, I would type `https://www.google.com/maps/search/?api=1&NUS+Museum` (It actually works, lol. Even I am surprised myself for some reason! :x)

So, in my Address App, I would make the first part of the default Google Map search query as `https://www.google.com/maps/search/?api=1&` and maybe specify another String constant such as `USER_QUERY` or something like that.

I would then need the app to communicate with Google Maps via https. Hence, I am not sure if I even need to make use of Google Maps API in the first place? (i.e. from my understanding, no need to modify the build.gradle file in my project?)

SO, my last question is. would I need to request access to Google Maps API here in this forum? Probably not right? :)

**Comment by tshradheya** [comment]
From your description, I assume that you will be using the Browser Panel to show the Google Map. In that case you won't need to request for the Google Maps API :)

**Comment by ghost** [comment]
Hi TA, thank you for your input. It makes sense =)

Yup, I think we definitely need our features to interact with the Browser Panel for the features to be apparent

**Comment by ghost** [comment]
Hi, from this website, I realized I got the format of the URL to be sent to the Google Maps server wrong. It should be of this format: `https://www.google.com/maps/search/?api=1&query=` with what I want to search behind after the url. For example, to search for the location of "NUS Museum", a URL like https://www.google.com/maps/search/?api=1&query=NUS+Museum would work. And from there, the server probably sends back a JSON code and by searching for the necessary parameters, let's say "address", I can get the exact address of the location after it. OR, a workaround would be possibly to show the results of the Google Maps search result on the Browser Panel directly?

I also refer to this https://en.wikipedia.org/wiki/List_of_HTTP_status_codes and I asked my tutor if the status code value of 200 is correct for "https" also and he said he thinks so.
![image](https://user-images.githubusercontent.com/35895966/38143161-d613a3ce-3471-11e8-9204-8e8cdd74de73.png)

Other links I referred to include (for info and etc) include: https://en.wikipedia.org/wiki/HTTPS#External_links, https://docs.oracle.com/javase/8/docs/api/index.html?javax/net/ssl/HttpsURLConnection.html and https://docs.oracle.com/javase/8/docs/api/java/net/URLEncoder.html. The reason for the URLEncoder class is because the format of the query should be in a URL-escaped string format. So, for example a whitespace character or ' ' becomes a '+' so that is why a string like "NUS Museum" will become "NUS+Museum"

I just hope I am going in the right direction!

**Comment by yamgent** [comment]
Hi, I am not sure whether a question is being asked by you here, so I need some clarifications from you in case it is: 

* Are you trying to utilise Google to help you do address translation? (i.e. suppose a contact has the address "NUS Museum", you are trying to use Google to help you to convert it to "50 Kent Ridge Cres, Singapore 119279")
* Or are you just trying to show a map of the address on your `BrowserPanel`, and you would just like to use Google Maps to do so?

---

> I also refer to this https://en.wikipedia.org/wiki/List_of_HTTP_status_codes and I asked my tutor if the status code value of 200 is correct for "https" also and he said he thinks so.

Yes, when a server replies with the status 'HTTP 200', it means that your request is well received and it is sending you the response.

**Comment by ghost** [comment]
Hi,

I think either of the bullet-points are fine. (but I'm just curious, which one is easier? haha..)

However, right now I even have trouble communicating with Google Maps server as I haven't learnt before.

Lastly, the HTTP 200 also works for HTTPS URL connections?

**Comment by yamgent** [comment]
> I think either of the bullet-points are fine. (but I'm just curious, which one is easier? haha..)
> 
> However, right now I even have trouble communicating with Google Maps server as I haven't learnt before.

The second point would be simpler in that case since it only involves making the `BrowserPanel` visiting a URL. 

The first point is a bit more advanced, but in case you are interested, I suggest try googling "Google Places API".

> Lastly, the HTTP 200 also works for HTTPS URL connections?

Yes, it is the same for both HTTP and HTTPS.

**Comment by ghost** [comment]
Okay! I think I understood roughly. Yup, `Browser Panel`, as its name suggests, could also act like a `web browser` if needed to, but in my case, I just want to show the Google Maps search result. I will of course try to make it as "CLI" as much as possible.

Perhaps, one suggestion is to use a command like `find location QUERY_PARAMETERS` where `QUERY_PARAMETERS` would be the name of the place you are searching for, for e.g. "NUS Museum". And after typing that command, the string "Searching location..." could be printed and after it has been found, the string "Location found!" would appear on the `Browser Panel`.

I think that since I would still need to interact with Google Maps web server, I would need to handle JSON scripts and also create a class or classes to handle them.
