### ISSUE TITLE
How to get a picture to appear on the Browser Panel?

### ISSUE THREAD

**Issue by ghost** [nus-cs2103-AY1718S2/forum#39]
Any idea on how to get a picture stored inside `\src\main\resources\images` to appear on the Browser Panel thru this command `motivate` on the CLI?

**Comment by kokonguyen191** [comment]
The approach that I first thought of when I saw this question is to hardcode a method that takes in an image or image url and returns a HTML String, then you loads the HTML directly into the `WebView` (can get from `BrowserPanel`).
Actually, I doubt if there is any other way as you can't really load an image directly into a `WebView`. It's a `WebView` after all.

**Comment by ghost** [comment]
Hi, thanks for the reply. Ya, I do feel this sort of major enhancement still has some sort of "learning curve" involved. For example, now, it is to learnt about HTML. I do know the long form of the abbreviation but things like the syntax of it I am as good as a newbie. Of course, I still have to learn it.

I went back to take a look a bit back at previous my Location Finder enhancement and realized learning about the JSON thingy and etc, it is a little possible. Moreover, one of my group members' major enhancement is to get a timetable link from NUSMods and they managed to do it and show it in the browser panel too, I think?

However, perhaps, in the first place, a major should have higher difficulty to implement than a minor one. Depending on what kind of major enhancement a student is implementing (and I believe most have already implemented theirs and in the stage of refining theirs, not saying I haven't, but I believe mine is still quite bare... /gasps/), one might have to learn new things they have not learnt (especially those with programming background that is only limited to C from CS1010 and Java from CS1020, along with a little bit of C++. Basically only started learning coding after enrolling into a CS-related course in university), there is perhaps no escaping learning now things and concepts. However, my worry is just the time left only though, but I just try to simplify the problem by tackling it in stages I guess.

Things like JS is probably not that hard, as I think it is a little related to Java (somewhat I guess?) but there are differences. Other things like XML formatted documents, fxml etc... , some students also probably found themselves learning how to create/modify one from looking at the syntax of an existing `.fxml` files in the project. I have probably came across this `.xml` extension before but never really knew or bothered what it do, aside from clicking files that can be opened out of curiosity..

**Comment by ahmadsyafiqruhazat** [comment]
Hi you can try [this](https://stackoverflow.com/questions/22984430/javafx2-webview-and-in-memory-images)
