### ISSUE TITLE
Travis test fails but passes locally for mail server

### ISSUE THREAD

**Issue by glorialaw** [nus-cs2103-AY1718S2/forum#41]
When I run the tests locally, all of the tests pass but the addCommandSystemTest seems to fail according to Travis for this PR: https://github.com/CS2103JAN2018-W10-B2/main/pull/53.

**Comment by tshradheya** [comment]
Can you try updating your gradle version to 4.6?

**Comment by glorialaw** [comment]
How do I do that?

**Comment by tshradheya** [comment]
Change this line https://github.com/nus-cs2103-AY1718S2/addressbook-level4/blob/master/build.gradle#L66

**Comment by glorialaw** [comment]
I made some changes and now I get the "java.lang.AssertionError: ATTENTION!!!! : On some computers, this test may fail when run on non-headless mode as FxRobot#clickOn(Node, MouseButton...) clicks on the wrong location. We suspect that this is a bug with TestFX library that we are using. If this test fails, you have to run your tests on headless mode. See UsingGradle.adoc on how to do so." error. But when I looked in the build.gradle file it seems to already be headless but the pointer is not going to the right place.

**Comment by tshradheya** [comment]
To run tests in headless mode, you need to type this in CLI `gradlew clean headless allTests`

Also for updating gradle on local, you may need to change this line as well https://github.com/nus-cs2103-AY1718S2/addressbook-level4/blob/master/gradle/wrapper/gradle-wrapper.properties#L6

**Comment by glorialaw** [comment]
Which file would I type gradlew clean headless allTests in?

**Comment by tshradheya** [comment]
> Which file would I type gradlew clean headless allTests in?

In the Terminal
