### ISSUE TITLE
Suggestion regarding the issue if a student happens to join CS2103/T late in subsequent iterations of the module

### ISSUE THREAD

**Issue by ghost** [nus-cs2103-AY1718S2/forum#45]
Hi, so I am a student who happened to find myself in a situation where I joined CS2103T at start of week 3 [probably the last student to join? it was after CORS bidding round 3B (or C in sem 2?). I actually monitored and have sort of been monitoring the class enrollment size of CS2103/T on IVLE sometimes). I hope I'm not complaining, but I want to suggest something :)

I understand CS2103/T has a very strict policy regarding enrollment of students like for example everyone must be in groups of 4 (or maybe 5 in other previous semesters).

The problem is that I found myself having to join it late due to some unmentioned reasons. Of course I am glad and happy that I still managed to secure a place as CS2103T is a very important core module for my graduation requirements.

The problem is, I had to catch up a lot after I joined [ and I also missed the first 2 lectures :( ]. Moving forward though, what's done is done. And also, it was actually the module administrator and not coordinator side that allowed me to join the module. Some could say if I really wanted to enroll in CS2103T this semester, why not look at the website from week 1 (since it is open-source)? Well, it was pretty confusing for me too, haha, because I already set my mind that I would do 2 other modules instead of CS2101 + CS2103T.

Lastly, actually, I am actually quite peace-loving. It has not been really easy but I still think it was a good experience? I also don't know why I wrote this, especially when I should just buckle down and try to finish whatever I can, but I have been quite unlucky this semester :/. Also, in future, the people who is teaching the module might change, but I believe Prof Damith should be still monitoring this module in future? (if possible, could we have arrange a meeting after the project period ends whereby I just talk about my experience this semester, just limited to myself I mean). In a way, actually I do consider myself having passion for SE but maybe talk itself is cheap.

Oh, writing until here I forgot about my suggestion. My suggestion is that, if any situation like mine happens similarly in future, perhaps, for the sake and sanity of the student, it would be better to still enforce the "strict policy"? It would also be better for the phase A & B (or even C if there is for other sems) team too :). Just my 2 cents though. 

![image](https://user-images.githubusercontent.com/35895966/38572188-02a86972-3d25-11e8-91e7-2562f3975b13.png)

**Comment by damithc** [comment]
@HEARTOFAL1ON Thanks for bringing this up. Please contact me after the semester is over so that we can meet up to discuss your feedback about the module that might be useful for future iterations.
