### ISSUE TITLE
Problem with running command "gradlew processResources"

### ISSUE THREAD

**Issue by ghost** [nus-cs2103-AY1718S2/forum#50]
Hi all, I am using a brand new notebook. It runs on Windows 8. When I try to run `gradlew processResources`, this happens
![image](https://user-images.githubusercontent.com/35895966/38712745-38a5c2ea-3f00-11e8-9692-0d299a44fb5e.png)

I have tried a lot of things including setting the `JAVA_HOME` as shown in the instructions from #19 (http://www.baeldung.com/java-home-on-windows-7-8-10-mac-os-x-linux) and also from https://javatutorial.net/set-java-home-windows-10 after Googling.
![image](https://user-images.githubusercontent.com/35895966/38712794-7b67b250-3f00-11e8-9370-6b71bd2f3f09.png)

Under `System variables`, I clicked on the variable named `Path` and then on `edit` and made necessary changes to path values.
![image](https://user-images.githubusercontent.com/35895966/38712826-b11b95ec-3f00-11e8-8c9b-afac6fc8979a.png)

On cmd.exe, I tested if the Java path works as intended and it should be correct as shown below:
![image](https://user-images.githubusercontent.com/35895966/38712849-dc65f21a-3f00-11e8-8dd0-6ddc5d272636.png)

Gradle and Git should also work as intended:
![image](https://user-images.githubusercontent.com/35895966/38712876-fd797c60-3f00-11e8-81d6-b9c6a875b000.png)
![image](https://user-images.githubusercontent.com/35895966/38712902-1e9091ae-3f01-11e8-9944-53cef933692b.png)

Hence, I am not sure what is the problem still. It is a bit urgent because I believe without being able to run `gradlew processResources` I cannot really work on anything and time is really short >< (!!!). Well, technically, I can, however, I believe if I don't run that command, there might be problems running `MainApp.main()` later like last time for example where an `input stream must not be null error` occurred or something like that... Previously, I was a Windows 8.1 user before my old notebook's motherboard was spoilt, but I don't think that really makes much of a difference whether WIN10 or WIN8. However, it seems setting up the Java path in WIN10 is a bit more complicated, is it?

Oh, by the way, one last thing, it is not really necessary to add `.java` to the value of the `system environment variable` called `PATHEXT` right?
![image](https://user-images.githubusercontent.com/35895966/38713015-abf6b1f4-3f01-11e8-8994-a7233db6e5a5.png)

**Comment by ghost** [comment]
Before I forget, I hope I also set the default project structure of the Java SDK correctly too:
![image](https://user-images.githubusercontent.com/35895966/38713086-fe549a92-3f01-11e8-8673-4ef8d447159a.png)

BY THE WAY, if we already installed JDK 8, there is no need to install JE 8 too right? Cuz I noticed JDK also comes with JRE by default too already?
![image](https://user-images.githubusercontent.com/35895966/38713112-236588be-3f02-11e8-8770-fc286cf26db6.png)
![image](https://user-images.githubusercontent.com/35895966/38713127-35ab53a0-3f02-11e8-9536-26bb282d9474.png)

Meanwhile, I will still continue trying to debug this problem (these problems) on my own.

**Comment by ghost** [comment]
I really apologize for the (possibly) influx of information :x....

Anyways, on IntelliJ, I realized they asked me where the location of the `git.exe` is so I had to download it. After doing necessary steps, on IntelliJ->Settings->Version Control->Git, I did this:
![image](https://user-images.githubusercontent.com/35895966/38713462-d8421be8-3f03-11e8-8860-77dc7c3f01bb.png)
(however I thought that SourceTree already comes with embedded Git. When installing SourceTree, it did ask if I wanted to install system git or something like that, but I did not select the option)

Just to show, I think the automatic building when I first opened the project and before running the command `gradlew processResources` which does not work, it worked fine I think.
![image](https://user-images.githubusercontent.com/35895966/38713604-8ff84f64-3f04-11e8-8ce8-68ca156a417d.png)

**Comment by pyokagan** [comment]
Can you run `gradlew processResources` on `cmd.exe`? If you are able to and it succeeds, then that would be sufficient enough.

**Comment by ghost** [comment]
Hi there, thank your for the reply.
Nope, not able to.
![image](https://user-images.githubusercontent.com/35895966/38721383-916b67c8-3f2c-11e8-81b4-02c6d851ea61.png)

Is everything correct here?
![image](https://user-images.githubusercontent.com/35895966/38721700-c1c9f550-3f2d-11e8-9a2a-aec1cb98de17.png)
![image](https://user-images.githubusercontent.com/35895966/38721759-ebcb11e0-3f2d-11e8-8ccc-edc3a60d7772.png)

**Comment by ghost** [comment]
I think I may know the problem, perhaps I did not set up my Gradle wrapper properly this time which is why any commands beginning with `gradlew` does not work?

**Comment by okkhoy** [comment]
If I am not wrong, you don't have to set up Gradle wrapper.
When you clone addressbook (or your project for that matter) it should come with a `gradlew` and `gradlew.bat` files. They are sufficient. 

Please check if you are in the correct folder when you run `gradlew processResources` on the command line.

**Comment by ghost** [comment]
Hi thanks Akshay and Paul. If I cloned addressbook to `Desktop`, does it matter? Will it cause problems? Should I have cloned the repo to `My Documents` or something?

**Comment by okkhoy** [comment]
I don't think that is a problem. In the worst case, your desktop will be cluttered.

**Comment by yamgent** [comment]
Just a shot in the dark. Do the following:

![gradle_project_75](https://user-images.githubusercontent.com/3168908/38744727-23ebed78-3f75-11e8-9822-3a1ee5907d2b.png)

1. Find the `Gradle project` pane, it should be on the right side of your IDE by default.
    a. If it is not visible by default, use the menu `View` > `Tool Windows` > `Gradle`.
1. Expand `Tasks` > `other`.
1. Double-click `processResources`.

What do you see?

**Comment by Zhiyuan-Amos** [comment]
~~You should be executing gradle and not gradlew btw :P~~

Edit: Oops wasn't thinking straight, sorry!

**Comment by ghost** [comment]
Hi all, resolved. A friend told me to restart my computer after modifying the environment variables but **I totally forgot about it**. Running `gradlew` on IntelliJ works now, so `gradlew processResources` should work too.

In ss below, top one output was after simply running `gradlew`:
![image](https://user-images.githubusercontent.com/35895966/38764676-0b0dca9e-3fe6-11e8-91c3-472cf1efc297.png)

**Comment by ghost** [comment]
`javac` and `java` works in terminal in IntelliJ IDEA too now:
![image](https://user-images.githubusercontent.com/35895966/38764687-4d2bd588-3fe6-11e8-897f-8c32ab60546f.png)
![image](https://user-images.githubusercontent.com/35895966/38764690-579d24cc-3fe6-11e8-91c2-2f32e39d6926.png)

and so does `echo %JAVA_HOME%` and `echo %PATH%` (they worked perfectly on `cmd.exe` previously):
![image](https://user-images.githubusercontent.com/35895966/38764705-8d65afca-3fe6-11e8-8710-0c190380c4d6.png)
