### ISSUE TITLE
runtests.bat outputs empty actual.txt

### ISSUE THREAD

**Issue by KevinChuangCH** [nus-cs2103-AY1718S2/forum#9]
After following the guide on setting up Address Book Level 2, running the runtests.bat still results in an empty actual.txt being created. 
This is the message on PowerShell.
![untitled](https://user-images.githubusercontent.com/35590287/36070799-b748c810-0f3d-11e8-8160-94be09e19d38.png)

Running all the test again after changing the config according to step 11 of the guide :
![1](https://user-images.githubusercontent.com/35590287/36070853-defdd156-0f3e-11e8-9396-94d0e1018ffe.png)

Running all the test again, but by "right-click the test folder, and click Run 'All Tests' ".
![2](https://user-images.githubusercontent.com/35590287/36070857-e7b9b044-0f3e-11e8-8b64-cffc4ce02f25.png)
![3](https://user-images.githubusercontent.com/35590287/36070858-e8a08d16-0f3e-11e8-8688-2b3531512007.png)

The following are my java version and the system setting screen shots:
![5](https://user-images.githubusercontent.com/35590287/36070942-1a7e4f6a-0f41-11e8-9364-85a416f6df32.png)
![4](https://user-images.githubusercontent.com/35590287/36070943-1b739736-0f41-11e8-97dc-6a3866ea02bd.png)

**Comment by KevinChuangCH** [comment]
The problem is solved by changing the java version from 9 to 1.8.0.
Apparently, the version change takes a while to register, for my computer at least.

**Comment by takuyakanbr** [comment]
Changes to environment variables won't be reflected in existing cmd / powershell instances. You'll need to restart them to use the updated environment variables.
